---
- name: Converge
  hosts: all
  become: true

  pre_tasks:
    - name: Ensure build dependencies are installed (RedHat).
      ansible.builtin.dnf:
        name: "{{ item }}"
        state: present
      loop:
        - "@Development tools"
        - tar
        - unzip
      when: ansible_os_family == 'RedHat'

    - name: Update apt cache.
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: '600'
      when: ansible_os_family == 'Debian'
      changed_when: false

    - name: Ensure build dependencies are installed (Debian).
      ansible.builtin.apt:
        name: "{{ item }}"
        state: present
      loop:
        - build-essential
        - unzip
        - tar
        - sudo
      when: ansible_os_family == 'Debian'

  roles:
    - role: shaneholloman.daemonize
